fly/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import FlyIndexViews, FlyFormViews, FlyFlightsViews, FlyAboutUsViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',FlyIndexViews.as_view(), name = 'index'),
    path('index/',FlyIndexViews.as_view(), name = 'index'),
    path('form/',FlyFormViews.as_view(), name = 'form'),
    path('flights/',FlyFlightsViews.as_view(), name = 'flights'),
    path('about_us/',FlyAboutUsViews.as_view(), name = 'abouts_us'),
    path("trips/", include("flyApp.urls")),
]

flyApp/urls.py
from django.contrib import admin
from django.urls import path , include
from .api.router import router

from .views import      TripsListView   \
                    ,   TripsDetailView \
                    ,   TripsCreateView \
                    ,   TripUpdateView \
                    ,   TripDeleteView

app_name = "trip"

urlpatterns = [
    path("", TripsListView.as_view(), name="all"),
    path("create/", TripsCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", TripsDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", TripUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", TripDeleteView.as_view(), name="delete")

]

urlpatterns += router.urls

flyApp/models.py
from django.db import models

# Create your models here.

class Trip(models.Model):
    origin  = models.CharField(max_length=40)
    destination = models.CharField(max_length=40)
    date = models.DateField()

    def __str__(self):
        return f"The trip from {self.origin} to {self.destination} departs on {self.date}"

fly/views.py
from django.views.generic import TemplateView

class FlyIndexViews(TemplateView):
    template_name = 'index.html'

class FlyFormViews(TemplateView):
    template_name = 'form.html'

class FlyFlightsViews(TemplateView):
    template_name = 'flights.html'

class FlyAboutUsViews(TemplateView):
    template_name = 'about_us.html'

flyApp/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Trip

from django import forms

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


class TripsBaseView(View):
    template_name = 'trip.html'
    model = Trip
    fields = '__all__'
    success_url = reverse_lazy('trip:all')


class TripsListView(TripsBaseView,ListView):    
    # THIS ALLOWS ME TO CREATE A VIEW WITH THE TRIPS
    # Paginate
    paginate_by = 3  # num pages
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        trip_list = self.get_queryset()
        
        paginator = Paginator(trip_list, self.paginate_by)
        page = self.request.GET.get('page')
        
        try:
            trips = paginator.page(page)
        except PageNotAnInteger:
            # If the page parameter is not a number, show the first page
            trips = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), show last page of results
            trips = paginator.page(paginator.num_pages)
        
        context['trip_list'] = trips
        return context
    

class TripsDetailView(TripsBaseView,DetailView):
    template_name = "trip_detail.html"
    extra_context = {
        "type": "detail trip"
    }

class TripsCreateView(TripsBaseView,CreateView):
    template_name = "trip_create.html"
    extra_context = {
        "type": "Create trip"
    }
    
    # Change text field to date for date
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})
        return form


class TripUpdateView(TripsBaseView,UpdateView):
    template_name = "trip_create.html"
    extra_context = {
        "type": "Update Trip"
    }
    
    # Change text field to date for date
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})
        return form

class TripDeleteView(TripsBaseView,DeleteView):
    template_name = "trip_delete.html"
    extra_context = {
        "type": "Delete trip"
    }

viajes/views.py
from django.views.generic import TemplateView

class ViajesIndexViews(TemplateView):
    template_name = 'index.html'

class ViajesFormViews(TemplateView):
    template_name = 'form.html'

class ViajesFlightsViews(TemplateView):
    template_name = 'flights.html'

class ViajesAboutUsViews(TemplateView):
    template_name = 'about_us.html'

flyApp/templates/trip_create.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div>
        <h1>Crear viaje</h1>
        <form method="post">

            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ type }}" />

        </form>

        <a href="{% url 'trip:all' %}">Volver</a>
    </div>
</main>
{% endblock %}

flyApp/templates/trip_delete.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div>
        <h1>¿Desea eliminar el viaje?</h1>
        <h2>{{trip.nombre}}</h2>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ type }}" />
        </form>

        <a href="{% url 'trip:all' %}">Atras</a>
    </div>
</main>
{% endblock %}

flyApp/templates/trip_detail.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div>
        <h1>Detalles del viaje</h1>
            <p> Destino: {{trip.destination}}</p>
            <p> Origen: {{trip.origin}}</p>
            <p> Fecha: {{trip.date}}</p>

        <a href="{% url 'trip:all' %}">Atras</a>
    </div>
</main>
{% endblock %}

templates/about_us.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <!-- Main -->
    <div class="conteiner">
        <!-- div conteniner -->
        <aside>
            <!-- aside -->
            <img id="image-aside" src="{% static 'assets/images/photo-1.jpg' %}" alt="fly-welcome">
        </aside>

        <article>
            <!-- article -->
            <div class="welcome">
                <h1>Nuestro equipo</h1><br>
                <p> Nuestro equipo de expertos en turismo se ha embarcado en innumerables travesías
                    para reunir información valiosa, consejos prácticos y recomendaciones sinceras que te ayudarán a
                    convertir tus sueños de viaje en realidad. Desde consejos sobre cómo encontrar las mejores
                    ofertas
                    de vuelos y alojamiento hasta sugerencias para vivir experiencias auténticas y fuera de lo
                    común,
                    estamos aquí para ser tu compañero de viaje y facilitarte cada paso del camino.
                    Nuestro equipo se compone de la siguiente manera:
                <div id="userData"></div>
                </p>
            </div>

        </article>
    </div>
</main>
<!-- javascript -->
<script type="text/javascript" src="{% static 'assets/js/api.js' %}"></script>
{% endblock %}
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css files -->
    <link rel="stylesheet" href="{% static '/assets/css/mobile.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '/assets/css/tablet.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '/assets/css/notebook.css' %}" type="text/css">

    <title>Fly</title>
</head>



<body>
    <header>
        <!-- header -->

        <div class="menu-toggle" id="mobile-menu">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>

        <nav class="nav-menu">
            <ul>
                <li><a href="{% url 'index' %}">Inicio</a></li>
                <li><a href="{% url 'flights' %}">Imagenes</a></li>
                <li><a href="{% url 'abouts_us' %}">Quienes somos</a></li>
                <li><a href="{% url 'trip:all' %}">Viajes</a></li>
                <li><a href="{% url 'form' %}">Contacto</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}{% endblock %}

    <footer>
        <!-- footer -->
        <p> Volar por el mundo - 2023 - CodoAcodo </p>
    </footer>
    <!-- javascript -->
    <script type="text/javascript" src="{% static '/assets/js/hamburger.js' %}"></script>
</body>

</html>

templates/flights.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <!-- Main -->

    <div class="imagenes">
        <img src="{% static 'assets/images/bariloche.jpg' %}" alt="fly.b" class="fly1">
        <img src="{% static 'assets/images/cordoba.jpg' %}" alt="fly.c" class="fly2">
        <img src="{% static 'assets/images/misiones.jpg' %}" alt="fly.m" class="fly3">
        <img src="{% static 'assets/images/bs.as.jpg' %}" alt="fly.bs" class="fly4">
        <img src="{% static 'assets/images/jujuy.jpg' %}" alt="fly.j" class="fly5">
    </div>
</main>

<!-- javascript -->
{% endblock %}
</body>

</html>

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- envio formulario -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js">
</script>
<script type="text/javascript">
    (function () {
        emailjs.init("13c2jzh7zGyBVsWti");
    })();
</script>

<main>
    <!-- main -->
    <div class="conteiner">
        <!-- div container -->
        <aside>
            <!-- aside -->
            <img id="image-aside" src="{% static 'assets/images/photo-1.jpg' %}" alt="fly-welcome">

        </aside>
        <article>
            <!-- article -->
            <div class="form">
                <form action="">
                    <label for="name">Nombre:</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter your name" required>

                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter your mail" required>

                    <label for="message">Mensaje:</label>
                    <textarea class="form-control" id="message" rows="4" required></textarea>

                    <input type="submit" value="send" onclick="sendMail()">
                </form>
            </div>

        </article>
        <div>
</main>
<!-- javascript -->
<script type="text/javascript" src="{% static 'assets/js/form.js' %}"></script>
{% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <!-- Main -->
    <div class="conteiner">
        <!-- div conteniner -->
        <aside>
            <!-- aside -->
            <img id="image-aside" src="{% static '/assets/images/photo-1.jpg' %}" alt="fly-welcome">
        </aside>

        <article>
            <!-- article -->
            <div class="welcome">
                <h1>Bienvenido a nuestro Sitio de viajes</h1><br>
                <p> En nuestro sitio web de viajes, no solo te ofrecemos información detallada
                    sobre los destinos más emblemáticos del mundo, sino que también te
                    inspiraremos a explorar lugares menos conocidos. </p>
            </div>

        </article>
    </div>
</main>
<!-- javascript -->
{% endblock %}

</body>

</html>

templates/trip.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <!-- Main -->
    <div class="conteiner">
        <!-- div conteniner -->
        <aside>
            <!-- aside -->
            <img id="image-aside" src="{% static '/assets/images/photo-1.jpg' %}" alt="fly-welcome">
        </aside>

        <article>
            <!-- article -->
            <div class="welcome">
                <h2><a href="{% url 'trip:create' %}">Crear viaje</a></h2>
                <h1>Todos los Vijes</h1>
                <table>
                    <tr>
                        <th>Origen</th>
                        <th>Destino</th>
                        <th>Fecha</th>
                        <th>Detalles</th>
                        <th>Modificar</th>
                        <th>Eliminar</th>
                    </tr>
                    <tr>
                        {% for trip in trip_list%}
                        <td>
                            <p>{{trip.destination}}</p>
                        </td>
                        <td>
                            <p>{{trip.origin}}</p>
                        </td>
                        <td>
                            <p>{{trip.date}}</p>
                        </td>
                        <td><a href="{% url 'trip:detail' trip.id %}"><img class="icon-table"
                                    src="{% static '/assets/images/magnifier.png' %}" alt="Trulli"></a></td>
                        <td><a href="{% url 'trip:update' trip.id %}"><img class="icon-table"
                                    src="{% static '/assets/images/wrench.png' %}" alt="Wrench"></a></td>
                        <td><a href="{% url 'trip:delete' trip.id %}"><img class="icon-table"
                                    src="{% static '/assets/images/trash-1.png' %}" alt="Delete"></a></td>
                    </tr>
                    {% endfor %}
                </table>

                <!-- paginated -->

                <div class="pagination">
                    <span class="step-links">
                        {% if trip_list.has_previous %}
                        <a href="?page=1">&laquo; Primera</a>
                        <a href="?page={{ trip_list.previous_page_number }}">Anterior</a>
                        {% endif %}

                        <span class="current">
                            Página {{ trip_list.number }} de {{ trip_list.paginator.num_pages }}.
                        </span>

                        {% if trip_list.has_next %}
                        <a href="?page={{ trip_list.next_page_number }}">Siguiente</a>
                        <a href="?page={{ trip_list.paginator.num_pages }}">Última &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
    </div>

    </article>
    </div>
</main>
<!-- javascript -->
{% endblock %}

</body>

</html>